### ISSUE TITLE
AWS EKS empty S3 bucket FileNotFoundException

### ISSUE THREAD

**Issue by fabboe** [lightbend/spark-history-server-docker#5]
Hi all,

I'm hitting an issue where spark-history-server doesn't start on AWS EKS an empty S3 bucket as `logDirectory` unless there's an object existing on the bucket. Tried without trailing slash as well, as well as both slash variants with additional object keys.

I'm deploying with the stable helm [chart](https://github.com/helm/charts/tree/master/stable/spark-history-server) which has the S3 logdirectory examples/defaults as buckets with trailing slash so it's interesting we're hitting this. Also from other usages of hadoop.fs.s3a.S3AFileSystem within Spark I'd expect this to work.

The only custom thing I do is 
```
SPARK_HISTORY_OPTS: "-Dspark.hadoop.fs.s3a.endpoint=s3.eu-central-1.amazonaws.com -Dcom.amazonaws.services.s3.enableV4"
```

Any ideas what could cause this?

Thanks.

image version 2.4.0

```
2020-01-09 09:07:18 INFO  FsHistoryProvider:54 - History server ui acls disabled; users with admin permissions: ; groups with admin permissions
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.deploy.history.HistoryServer$.main(HistoryServer.scala:280)
	at org.apache.spark.deploy.history.HistoryServer.main(HistoryServer.scala)
Caused by: java.io.FileNotFoundException: Log directory specified does not exist: s3a://mybucket/
	at org.apache.spark.deploy.history.FsHistoryProvider.org$apache$spark$deploy$history$FsHistoryProvider$$startPolling(FsHistoryProvider.scala:267)
	at org.apache.spark.deploy.history.FsHistoryProvider.initialize(FsHistoryProvider.scala:211)
	at org.apache.spark.deploy.history.FsHistoryProvider.<init>(FsHistoryProvider.scala:207)
	at org.apache.spark.deploy.history.FsHistoryProvider.<init>(FsHistoryProvider.scala:86)
	... 6 more
Caused by: java.io.FileNotFoundException: No such file or directory: s3a://mybucket/
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:993)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:77)
	at org.apache.spark.deploy.history.FsHistoryProvider.org$apache$spark$deploy$history$FsHistoryProvider$$startPolling(FsHistoryProvider.scala:257)
```

**Comment by ganesancit** [comment]
Have the same issue on version 2.4.5
